name: Telegram Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify-telegram:
    runs-on: ubuntu-latest

    steps:
    - name: Enviar mensagem para o Telegram
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
        -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
        -d text="🚀 Um novo commit ou pull request foi feito na branch main do repositório Calculadora-Python!"
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
