name: Telegram Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Enviar mensagem para o Telegram
      run: |
        curl -s --data "chat_id=$TELEGRAM_CHAT_ID&text=Novo commit realizado no repositório! [Calculadora-Python]" \
        "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage"
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
