name: Telegram Alerts on Commit or Merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify-telegram:
    runs-on: ubuntu-latest

    steps:
    - name: Send message to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d chat_id=${TELEGRAM_CHAT_ID} -d text="🚀 A new commit or PR has been made to the main branch in the repository!"
