name: Mensagem Via Telegram
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: enviar mensagem
        uses: ./
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            O evento ${{ github.event_name }} com ID ${{ github.ref }} foi concluído com sucesso.
